#define CRYPTO_SECRETKEYBYTES 2417
#define CRYPTO_PUBLICKEYBYTES 1623
#define CRYPTO_CIPHERTEXTBYTES 1455
#define CRYPTO_BYTES 32
#define CRYPTO_ALGNAME "sntrup1013"

#include "crypto_kem_sntrup1013.h"

#define crypto_kem_keypair crypto_kem_sntrup1013_keypair
#define crypto_kem_enc crypto_kem_sntrup1013_enc
#define crypto_kem_dec crypto_kem_sntrup1013_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_sntrup1013_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_sntrup1013_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_sntrup1013_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_sntrup1013_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "sntrup1013"