#define CRYPTO_SECRETKEYBYTES 1463
#define CRYPTO_PUBLICKEYBYTES 1184
#define CRYPTO_CIPHERTEXTBYTES 1312
#define CRYPTO_BYTES 32
#define CRYPTO_ALGNAME "ntrulpr857"

#include "crypto_kem_ntrulpr857.h"

#define crypto_kem_keypair crypto_kem_ntrulpr857_keypair
#define crypto_kem_enc crypto_kem_ntrulpr857_enc
#define crypto_kem_dec crypto_kem_ntrulpr857_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_ntrulpr857_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_ntrulpr857_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_ntrulpr857_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_ntrulpr857_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "ntrulpr857"