#define CRYPTO_SECRETKEYBYTES 1294
#define CRYPTO_PUBLICKEYBYTES 1039
#define CRYPTO_CIPHERTEXTBYTES 1167
#define CRYPTO_BYTES 32
#define CRYPTO_ALGNAME "ntrulpr761"

#include "crypto_kem_ntrulpr761.h"

#define crypto_kem_keypair crypto_kem_ntrulpr761_keypair
#define crypto_kem_enc crypto_kem_ntrulpr761_enc
#define crypto_kem_dec crypto_kem_ntrulpr761_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_ntrulpr761_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_ntrulpr761_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_ntrulpr761_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_ntrulpr761_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "ntrulpr761"
