#include "api.h"
#include "parameters.h"

#define KECCAK_MAX_MESSAGE_BYTESIZE CRYPTO_CIPHERTEXTBYTESIZE

// SHAKE256 profile //

#define SHAKE256_RATE_BYTESIZE 136
#define SHAKE256_RATE_64BIT_SIZE 17
#define KECCAK_STATE_64BIT_SIZE 25
#define PRNG_STATE_64BIT_SIZE 26
