# this is help print for test_all.sh (using test_all_param.sh)

echo "   usage: ./test_all2.sh -cbr 2 -a '0 1 2 2'"
echo ""
echo "   -a:str  pass old style 'x x x x' (0-2)"
echo "           (doValgrindFull, doValgrindKeygen, doValgrindEnc, doValgrindDec)"
echo "           (default '0 1 1 1')"
echo "   -b      do build"
echo "   -c      do clean before build"
echo "   -r:n    KAT repeats runs (default 10)"
echo "   -d      optional debug KAT"
echo "   -e      optional debug KAT_keygen"
echo "   -f      optional debug KAT_enc"
echo "   -g      optional debug KAT_dec"
echo "   -i      optional debug verifyKat"
echo "   -v      same as: -a '0 2 2 2'   (override -a)"
echo ""
echo " ------ from old test_all.sh:"
echo "4 parameter expected for valgrind control (doValgrindFull, doValgrindKeygen, doValgrindEnc, doValgrindDec)"
echo " doValgrind*: 0 = nothing at all (base KAT is always executed)"
echo " doValgrind*: 1 = run KAT without valgrind"
echo " doValgrind*: 2 = run KAT with valgrind"
echo "example: $ ./test_all.sh 0 1 0 0   --> will do only keygen KAT without valgrind"
echo "example: $ ./test_all.sh 0 2 0 0   --> will do only keygen KAT with valgrind"
echo "example: $ ./test_all.sh 0 0 0 0   --> no valgrind, only base KAT executed"
echo "example: $ ./test_all.sh 0 1 1 1   --> no valgrind, all KAT executed"
echo "example: $ ./test_all.sh 0 2 2 2   --> will do valgrind keygen, encoding and decoding"
echo "example: $ ./test_all.sh 0 2 2 1   --> will do valgrind keygen and encoding and no valgrind decoding"