#define CRYPTO_SECRETKEYBYTES 1763
#define CRYPTO_PUBLICKEYBYTES 1158
#define CRYPTO_CIPHERTEXTBYTES 1039
#define CRYPTO_BYTES 32
#define CRYPTO_ALGNAME "sntrup761"

#include "crypto_kem_sntrup761.h"

#define crypto_kem_keypair crypto_kem_sntrup761_keypair
#define crypto_kem_enc crypto_kem_sntrup761_enc
#define crypto_kem_dec crypto_kem_sntrup761_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_sntrup761_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_sntrup761_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_sntrup761_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_sntrup761_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "sntrup761"