#define CRYPTO_SECRETKEYBYTES 2231
#define CRYPTO_PUBLICKEYBYTES 1847
#define CRYPTO_CIPHERTEXTBYTES 1975
#define CRYPTO_BYTES 32
#define CRYPTO_ALGNAME "ntrulpr1277"

#include "crypto_kem_ntrulpr1277.h"

#define crypto_kem_keypair crypto_kem_ntrulpr1277_keypair
#define crypto_kem_enc crypto_kem_ntrulpr1277_enc
#define crypto_kem_dec crypto_kem_ntrulpr1277_dec
#define crypto_kem_PUBLICKEYBYTES crypto_kem_ntrulpr1277_PUBLICKEYBYTES
#define crypto_kem_SECRETKEYBYTES crypto_kem_ntrulpr1277_SECRETKEYBYTES
#define crypto_kem_BYTES crypto_kem_ntrulpr1277_BYTES
#define crypto_kem_CIPHERTEXTBYTES crypto_kem_ntrulpr1277_CIPHERTEXTBYTES
#define crypto_kem_PRIMITIVE "ntrulpr1277"